# Generated by Django 3.2.12 on 2022-10-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('cours', models.CharField(max_length=255)),
                ('numbers', models.IntegerField()),
                ('numbers_parent', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
