# Generated by Django 3.2.12 on 2022-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='numbers',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='numbers_parent',
            field=models.PositiveBigIntegerField(),
        ),
    ]
